import { useEffect, useState } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { Circle, CircleMarker, Polyline, Popup, useMapEvents } from 'react-leaflet';
import { MapPin, ShieldCheck, Bell, Send, Download, Check, Home, ArrowUpRight, Navigation, Users, ExternalLink } from 'lucide-react';
import { CycloneMap } from '../components/maps/CycloneMap';
import { API_BASE_URL } from '../services/api';
import { useResearchResource, utc } from '../services/research';
import './coastal-tools.css';

type Source={name:string;url:string};
type Shelter={id:string;name:string;lat:number;lon:number;district:string;type:string;distanceKm:number;openStatus:string;mapUrl:string};
type Nearby={shelters:Shelter[];totalNearby:number;sourceUrl:string;retrievedAt:string;coverage:string};
type Plan={createdAt:string;location:{lat:number;lon:number;label:string};householdSize:number;status:string;selectedShelter:Shelter|null;destinationConfirmedByUser:boolean;steps:{stage:string;items:string[]}[];routeStatus:string;note:string;sources:Source[]};
type Draft={id:string;kind:string;headline:string;message:string;issuedAt:string;expiresAt:string;recipientCount:number;sourceUrl:string;districtReferences:{name:string;state:string;distanceKm:number}[];area:{points:[number,number][];radiusKm:number;note:string};forecast?:{name:string;issuedAt:string};expired?:boolean};
type Subscription={id:string;token:string;label:string};
type Status={smsConfigured:boolean;directoryCount:number;directoryRetrievedAt:string;coverage:string;sources:Source[]};
const STORAGE='cyclone-area-subscription-v1';
async function request<T>(path:string,body?:unknown,headers:Record<string,string>={}):Promise<T>{const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),30000);try{const response=await fetch(`${API_BASE_URL}/planning${path}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal,cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check the supplied fields and try again.');return data;}finally{window.clearTimeout(timer);}}
function planText(p:Plan):string { return [`CYCLONE AI · HOUSEHOLD PREPAREDNESS PLAN`,p.status,`Prepared: ${utc(p.createdAt)}`,`Location: ${p.location.label} (${p.location.lat}, ${p.location.lon})`,`People: ${p.householdSize}`,`Destination: ${p.selectedShelter?`${p.selectedShelter.name}, ${p.selectedShelter.district}; ${p.selectedShelter.lat}, ${p.selectedShelter.lon}`:'Not confirmed'}`,p.routeStatus,...p.steps.flatMap(s=>['',s.stage,...s.items.map(i=>`[ ] ${i}`)]),'','Immediate emergency in India: 112',p.note,...p.sources.map(s=>`${s.name}: ${s.url}`)].join('\n'); }
function pickInitial(value:string|null,fallback:number,min:number,max:number){if(value==null)return fallback;const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=min&&parsed<=max?parsed:fallback;}
function loadSubscription():Subscription|null{try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');return v&&typeof v.id==='string'&&typeof v.token==='string'?v:null;}catch{return null;}}
function MapPick({onPick}:{onPick:(lat:number,lon:number)=>void}){useMapEvents({click:e=>onPick(Number(e.latlng.lat.toFixed(3)),Number(e.latlng.lng.toFixed(3)))});return null;}

function Inbox({subscription,onRemove}:{subscription:Subscription;onRemove:()=>void}){
  const [alerts,setAlerts]=useState<Draft[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [refresh,setRefresh]=useState(0);
  useEffect(()=>{let alive=true;const read=()=>request<{alerts:Draft[]}>(`/subscriptions/${subscription.id}/inbox`,undefined,{'X-Subscription-Token':subscription.token}).then(v=>{if(alive){setAlerts(v.alerts);setError('');}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});void read();const timer=window.setInterval(read,30000);return()=>{alive=false;window.clearInterval(timer);};},[subscription.id,subscription.token,refresh]);
  return <section className="coastal-panel"><div className="coastal-panel-title"><div><span className="eyebrow">YOUR AREA INBOX</span><h2>{subscription.label}</h2></div><Bell size={24}/></div><p>Messages are targeted to your saved area. This inbox updates every 30 seconds.</p><div className="coastal-actions"><button className="coastal-button secondary" onClick={()=>setRefresh(v=>v+1)}>Refresh inbox</button><button className="coastal-text-button" onClick={async()=>{try{await request(`/subscriptions/${subscription.id}/unsubscribe`,{}, {'X-Subscription-Token':subscription.token});onRemove();}catch(e){setError(e instanceof Error?e.message:'Could not unsubscribe.');}}}>Unsubscribe & delete location</button></div>{error&&<p role="alert" className="coastal-message">{error}</p>}{loading?<p role="status">Loading your messages…</p>:!alerts.length?<div className="coastal-empty"><Bell size={26}/><h3>No messages for this area yet</h3><p>An empty inbox does not mean an area is safe. Continue checking official advisories.</p></div>:alerts.map(a=><article className="inbox-alert" key={a.id}><span className={`coastal-tag ${a.kind==='exercise'?'exercise':''}`}>{a.kind==='exercise'?'EXERCISE · NOT CURRENT':'RELAYED ADVISORY'}{a.expired?' · EXPIRED':''}</span><h3>{a.headline}</h3><p>{a.message}</p><small>Expires {utc(a.expiresAt)}</small><a href={a.sourceUrl} target="_blank" rel="noreferrer">Official source ↗</a></article>)}</section>;
}

export default function CoastalPlanner(){
  const [params]=useSearchParams();const [tab,setTab]=useState(params.get('tab')==='warnings'?'warnings':'plan');
  const [lat,setLat]=useState(String(pickInitial(params.get('lat'),19.8135,-90,90)));const [lon,setLon]=useState(String(pickInitial(params.get('lon'),85.8312,-180,180)));const [label,setLabel]=useState(params.has('lat')?'Selected map location':'Puri example — choose your location');
  const [location,setLocation]=useState({lat:Number(lat),lon:Number(lon),label});const [locationError,setLocationError]=useState('');
  const [people,setPeople]=useState(1);const [mobility,setMobility]=useState(false);const [children,setChildren]=useState(false);const [pets,setPets]=useState(false);const [transport,setTransport]=useState('private');const [shelterId,setShelterId]=useState('');const [confirmed,setConfirmed]=useState(false);const [showAll,setShowAll]=useState(false);
  const [plan,setPlan]=useState<{key:string;data:Plan}|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const {data:nearby,error:shelterError}=useResearchResource<Nearby>(`/planning/shelters?lat=${location.lat}&lon=${location.lon}&radiusKm=50`);
  const {data:status}=useResearchResource<Status>('/planning/status');const {data:districts}=useResearchResource<{districts:{id:string;name:string;state:string;centroid:[number,number]}[]}>('/districts/coastal');
  const [subscription,setSubscription]=useState<Subscription|null>(loadSubscription);const [phone,setPhone]=useState('');const [consent,setConsent]=useState(false);
  const [kind,setKind]=useState('exercise');const [geometry,setGeometry]=useState('forecast');const [radius,setRadius]=useState(100);const [headline,setHeadline]=useState('Coastal preparedness exercise');const [message,setMessage]=useState('');const [sourceUrl,setSourceUrl]=useState('');const [issued,setIssued]=useState('');const [expires,setExpires]=useState('');const [operatorKey,setOperatorKey]=useState('');const [channel,setChannel]=useState('in_app');
  const [draft,setDraft]=useState<{key:string;data:Draft}|null>(null);const [reviewed,setReviewed]=useState(false);const [delivery,setDelivery]=useState('');
  const planPayload={...location,people,mobility,children,pets,transport,shelterId:shelterId||null,shelterConfirmed:confirmed};const planKey=JSON.stringify(planPayload);const currentPlan=plan?.key===planKey?plan.data:null;
  const draftPayload={...location,kind,geometry,radiusKm:radius,headline,message,sourceUrl,issuedAt:issued?new Date(issued).toISOString():null,expiresAt:expires?new Date(expires).toISOString():null};const draftKey=JSON.stringify(draftPayload);const currentDraft=draft?.key===draftKey?draft.data:null;
  const activeShelter=nearby?.shelters.find(s=>s.id===shelterId);
  const updateLocation=(newLat:number,newLon:number,newLabel=label)=>{setLat(String(newLat));setLon(String(newLon));setLabel(newLabel);setLocation({lat:newLat,lon:newLon,label:newLabel});setShelterId('');setConfirmed(false);setLocationError('');setDelivery('');};
  const useCoordinates=(e:React.FormEvent)=>{e.preventDefault();const a=Number(lat),b=Number(lon);if(!lat.trim()||!lon.trim()||!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a)>90||Math.abs(b)>180){setLocationError('Enter valid latitude and longitude.');return;}updateLocation(a,b);};
  const generatePlan=async()=>{setBusy(true);setError('');try{setPlan({key:planKey,data:await request<Plan>('/plan',planPayload)});}catch(e){setError(e instanceof Error?e.message:'Could not create plan.');}finally{setBusy(false);}};

  const createDraft=async()=>{setBusy(true);setError('');setDelivery('');setReviewed(false);try{setDraft({key:draftKey,data:await request<Draft>('/drafts',draftPayload,{'X-Operator-Key':operatorKey})});}catch(e){setError(e instanceof Error?e.message:'Draft failed.');}finally{setBusy(false);}};
  const publish=async()=>{if(!currentDraft)return;setBusy(true);setError('');try{const r=await request<{results:Record<string,number>;note:string}>(`/drafts/${currentDraft.id}/dispatch`,{channel,reviewed,confirmation:'SEND'},{'X-Operator-Key':operatorKey});setDelivery(Object.entries(r.results).map(([k,v])=>`${v} ${k}`).join(' · ')+'. '+r.note);setReviewed(false);}catch(e){setError(e instanceof Error?e.message:'Delivery failed.');}finally{setBusy(false);}};
  const saveSubscription=async()=>{setBusy(true);setError('');try{const r=await request<Subscription>('/subscriptions',{...location,phone:phone||null,consent});localStorage.setItem(STORAGE,JSON.stringify({id:r.id,token:r.token,label:r.label}));setSubscription(r);setPhone('');setConsent(false);}catch(e){setError(e instanceof Error?e.message:'Could not subscribe.');}finally{setBusy(false);}};

  return <div className="coastal-planner"><div className="coastal-heading"><div><span className="eyebrow">PREPAREDNESS STARTS WITH A PLACE</span><h1>A plan before the storm.</h1><p>Find official shelter candidates, prepare your household, and review warnings for a selected area.</p></div><ShieldCheck size={38}/></div>
  <nav className="coastal-tabs" aria-label="Planning tools">{[['plan','My evacuation plan',Home],['warnings','Area warning desk',Send],['inbox','My area inbox',Bell]].map(([id,name,Icon])=>{const I=Icon as typeof Home;return <button key={String(id)} className={tab===id?'selected':''} aria-pressed={tab===id} onClick={()=>{setTab(String(id));setError('');}}><I size={17}/>{String(name)}</button>;})}</nav>
  <div className="coastal-authority-note"><ShieldCheck size={19}/><p>Official instructions come first. Plans use directory locations; shelter opening, capacity and passable routes must be confirmed locally. In India, call <a href="tel:112">112</a> for immediate emergency assistance.</p><a href="https://sachet.ndma.gov.in/" target="_blank" rel="noreferrer">Official alerts <ExternalLink size={14}/></a></div>
  <section className="coastal-location-bar"><form onSubmit={useCoordinates}><label>Place label<input aria-label="Plan location label" maxLength={100} required value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Latitude<input aria-label="Plan latitude" type="number" step="any" min="-90" max="90" required value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input aria-label="Plan longitude" type="number" step="any" min="-180" max="180" required value={lon} onChange={e=>setLon(e.target.value)}/></label><button className="coastal-button" type="submit"><MapPin size={15}/>Use this location</button></form><div className="coastal-location-extras"><select aria-label="Choose coastal reference" defaultValue="" onChange={e=>{const d=districts?.districts.find(d=>d.id===e.target.value);if(d)updateLocation(d.centroid[0],d.centroid[1],`${d.name} reference point`);}}><option value="" disabled>Or choose a coastal reference point</option>{districts?.districts.map(d=><option key={d.id} value={d.id}>{d.name}, {d.state}</option>)}</select><button className="coastal-text-button" onClick={()=>{if(!navigator.geolocation){setLocationError('Location is not supported by this browser.');return;}navigator.geolocation.getCurrentPosition(p=>updateLocation(Number(p.coords.latitude.toFixed(3)),Number(p.coords.longitude.toFixed(3)),'My approximate location'),()=>setLocationError('Location unavailable or permission denied. Enter coordinates instead.'),{enableHighAccuracy:false,timeout:10000});}}>Use my location</button><small>Planning coordinates stay on this computer. GPS is requested only when you choose it.</small></div>{locationError&&<p role="alert">{locationError}</p>}<p className="coastal-location-current">Using <strong>{location.label}</strong> · {location.lat.toFixed(3)}°, {location.lon.toFixed(3)}°</p></section>
  {error&&<p role="alert" className="coastal-message error">{error}</p>}
  {tab==='plan'&&<><div className="coastal-plan-grid"><section className="coastal-panel"><div className="coastal-panel-title"><div><span className="eyebrow">01 / YOUR HOUSEHOLD</span><h2>What does your group need?</h2></div><Users size={23}/></div><div className="household-form"><label>People in your household<input type="number" aria-label="Household size" min={1} max={50} value={people} onChange={e=>setPeople(Number(e.target.value))}/></label><label>Transport<select aria-label="Transport needs" value={transport} onChange={e=>setTransport(e.target.value)}><option value="private">Private transport available</option><option value="walk">Walking only</option><option value="assistance">Need evacuation transport</option></select></label></div><div className="coastal-check-list"><label><input type="checkbox" checked={mobility} onChange={e=>setMobility(e.target.checked)}/>Mobility, medical or accessibility support</label><label><input type="checkbox" checked={children} onChange={e=>setChildren(e.target.checked)}/>Children in the group</label><label><input type="checkbox" checked={pets} onChange={e=>setPets(e.target.checked)}/>Pets or livestock need arrangements</label></div><div className="coastal-map"><CycloneMap center={[location.lat,location.lon]} zoom={10}><MapPick onPick={(a,b)=>updateLocation(a,b,'Selected map point')}/><CircleMarker center={[location.lat,location.lon]} radius={8} pathOptions={{color:'#163d53',fillOpacity:1}}><Popup>Your planning location</Popup></CircleMarker>{nearby?.shelters.map(s=><CircleMarker key={s.id} center={[s.lat,s.lon]} radius={s.id===shelterId?9:5} pathOptions={{color:s.id===shelterId?'#c88028':'#397f7a',fillOpacity:.7}}><Popup><strong>{s.name}</strong><br/>{s.distanceKm} km straight line<br/>Opening unknown</Popup></CircleMarker>)}</CycloneMap></div><p className="coastal-fine">Click the map to change your planning point. Green markers are official-directory entries, not confirmed safe destinations.</p></section>
  <section className="coastal-panel"><span className="eyebrow">02 / A DESTINATION TO CONFIRM</span><h2>Nearby shelter candidates</h2><p>{status?.directoryCount??'…'} entries from OSDMA · Odisha coverage. Distances are straight-line, not travel distances.</p>{shelterError?<p className="coastal-message" role="alert">{shelterError}</p>:!nearby?<p role="status">Finding nearby directory entries…</p>:!nearby.shelters.length?<div className="coastal-empty"><MapPin size={28}/><h3>No listed shelter within 50 km</h3><p>This registry covers Odisha only. Ask your district administration for its designated destination and transport plan; the absence of results does not mean no shelter exists.</p><a href="https://sachet.ndma.gov.in/" target="_blank" rel="noreferrer">Check official local alerts ↗</a></div>:<><div className="shelter-list">{nearby.shelters.slice(0,showAll?30:6).map(s=><button className={`shelter-candidate ${shelterId===s.id?'chosen':''}`} key={s.id} onClick={()=>{setShelterId(s.id);setConfirmed(false);}}><span className="shelter-icon">{shelterId===s.id?<Check size={18}/>:<Home size={18}/>}</span><span><strong>{s.name}</strong><small>{s.district} · {s.type}</small><em>Opening & capacity unverified</em></span><b>{s.distanceKm.toFixed(1)}<small>km</small></b></button>)}</div>{nearby.shelters.length>6&&<button className="coastal-text-button" onClick={()=>setShowAll(v=>!v)}>{showAll?'Show fewer':`Show ${nearby.shelters.length} nearest entries`}</button>}</>}
  {activeShelter&&<div className="candidate-detail"><strong>Selected candidate: {activeShelter.name}</strong><p>Confirm the exact building, opening, space, accessibility and route with local authorities before departure.</p><div className="coastal-actions"><a href={activeShelter.mapUrl} target="_blank" rel="noreferrer">View listed location <ArrowUpRight size={14}/></a><a href={`https://www.google.com/maps/dir/?api=1&destination=${activeShelter.lat},${activeShelter.lon}`} target="_blank" rel="noreferrer">View map directions <Navigation size={14}/></a></div><small>External directions do not account for verified cyclone hazards, flood closures or shelter status. No starting coordinates are included in this link.</small><label className="tool-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Local authorities have confirmed this destination and route for my household.</label></div>}
  <div className="shelter-source"><a href="https://www.osdma.org/shelter-locations/" target="_blank" rel="noreferrer">OSDMA source directory ↗</a><small>{nearby?`Retrieved ${utc(nearby.retrievedAt)}`:''}</small></div></section></div>
  <div className="plan-generate"><p>{activeShelter?`Build a household plan with ${activeShelter.name} as your ${confirmed?'user-confirmed destination':'candidate destination'}.`:'You can create a preparedness checklist now; the destination will remain unconfirmed.'}</p><button className="coastal-button" disabled={busy||people<1||people>50} onClick={generatePlan}>{busy?'Preparing…':'Create my plan'}</button></div>{plan&&!currentPlan&&<p role="status" className="coastal-message">Your inputs changed. Create the plan again to include your latest choices.</p>}
  {currentPlan&&<section className="plan-result coastal-panel"><div className="coastal-panel-title"><div><span className="eyebrow">YOUR HOUSEHOLD PLAN</span><h2>{currentPlan.location.label}</h2><p>{currentPlan.status}</p></div><div className="coastal-actions"><a className="coastal-button secondary" href={`${API_BASE_URL}/planning/plan.txt?${new URLSearchParams(Object.entries(planPayload).filter(([,value])=>value!==null).map(([key,value])=>[key,String(value)]))}`} download="cyclone-household-plan.txt"><Download size={16}/>Download plan</a><button className="coastal-text-button" onClick={()=>window.print()}>Print</button></div></div><div className="plan-destination"><Home size={24}/><div><strong>{currentPlan.selectedShelter?.name||'Destination not yet confirmed'}</strong><p>{currentPlan.selectedShelter?`${currentPlan.selectedShelter.district} · ${currentPlan.selectedShelter.distanceKm} km straight line`:'Contact your local authority for an open designated shelter.'}</p><small>{currentPlan.routeStatus}</small></div></div><details className="plan-text-export"><summary>Read or copy the full plan as text</summary><pre>{planText(currentPlan)}</pre></details><div className="plan-steps">{currentPlan.steps.map((step,i)=><article key={step.stage}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{step.stage}</h3><ul>{step.items.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div><p className="coastal-fine">{currentPlan.note} Created {utc(currentPlan.createdAt)}.</p></section>}</>}
  {tab==='warnings'&&<div className="warning-desk-grid"><section className="coastal-panel"><span className="eyebrow">01 / DEFINE AN AREA & MESSAGE</span><h2>Prepare an area warning</h2><p>Freeze the message and recipient area, review the draft, then choose delivery. Saved research forecasts create exercises only.</p><div className="warning-form"><label>Message type<select value={kind} onChange={e=>{setKind(e.target.value);setGeometry(e.target.value==='official'?'circle':'forecast');setReviewed(false);}}><option value="exercise">Local research exercise</option><option value="official">Relay a current official advisory</option></select></label><label>Target area<select aria-label="Warning target area" value={geometry} onChange={e=>setGeometry(e.target.value)}><option value="forecast" disabled={kind==='official'}>Along selected archived +24h model path</option><option value="circle">Around my planning location</option></select></label><label>Planning distance · {radius} km<input aria-label="Warning radius" type="range" min={5} max={300} step={5} value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><small>This distance is chosen by you; it is not a validated wind, flood or surge boundary.</small><label>Headline<input aria-label="Warning headline" maxLength={120} minLength={5} value={headline} onChange={e=>setHeadline(e.target.value)}/></label>
  {kind==='official'&&<><p className="coastal-message">For an authorized operator relaying an existing official advisory. The app does not issue evacuation orders or verify the advisory text automatically.</p><label>Official government advisory URL<input type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://…gov.in/…"/></label><label>Reviewed advisory message<textarea rows={5} maxLength={1200} value={message} onChange={e=>setMessage(e.target.value)}/></label><label>Issued at (your local time)<input type="datetime-local" value={issued} onChange={e=>setIssued(e.target.value)}/></label><label>Expires at (your local time)<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>Operator key<input type="password" autoComplete="off" value={operatorKey} onChange={e=>setOperatorKey(e.target.value)}/></label></>}
  <button className="coastal-button" disabled={busy||headline.trim().length<5} onClick={createDraft}>{busy?'Preparing…':'Preview targeted warning'}</button></div><p className="coastal-fine">Current SMS status: {status?.smsConfigured?'provider configured':'not configured — in-app exercises work now'}. No message is sent when you preview.</p></section>
  <section className="coastal-panel"><span className="eyebrow">02 / REVIEW & DELIVER</span><h2>A precise message. A known audience.</h2>{!currentDraft?<div className="coastal-empty"><Send size={28}/><p>{draft?'Inputs changed. Preview again before delivery.':'Create a preview to see the exact message, map and recipient count.'}</p></div>:<><span className={`coastal-tag ${currentDraft.kind==='exercise'?'exercise':''}`}>{currentDraft.kind==='exercise'?'EXERCISE · NO CURRENT THREAT CLAIM':'OFFICIAL ADVISORY RELAY'}</span><div className="warning-preview"><h3>{currentDraft.headline}</h3><p>{currentDraft.message}</p><small>Expires {utc(currentDraft.expiresAt)}</small></div><div className="warning-counts"><strong>{currentDraft.recipientCount}<small>opted-in area subscriptions</small></strong><strong>{currentDraft.districtReferences.length}<small>district reference points</small></strong></div><div className="coastal-map"><CycloneMap center={currentDraft.area.points[0]} zoom={5}>{currentDraft.area.points.length>1&&<Polyline positions={currentDraft.area.points} pathOptions={{color:'#ba803a',dashArray:'6 6'}}/>}{currentDraft.area.points.map((p,i)=><Circle key={i} center={p} radius={currentDraft.area.radiusKm*1000} pathOptions={{color:'#bb8548',fillOpacity:.09}}/>)}</CycloneMap></div><p className="coastal-fine">{currentDraft.area.note} Circles show endpoint distance only; recipients are calculated along the full guide line. {currentDraft.districtReferences.map(d=>d.name).join(', ')||'No reference centroids in this selection.'}</p><label className="warning-delivery-label">Delivery channel<select value={channel} onChange={e=>{setChannel(e.target.value);setReviewed(false);}}><option value="in_app">Opted-in local area inboxes</option><option value="sms" disabled={kind==='exercise'||!status?.smsConfigured}>SMS · verified recipients only</option></select></label><label className="tool-check review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the message, dates, selected area and {currentDraft.recipientCount} subscriptions.</label><button className="coastal-button" disabled={busy||!reviewed||!currentDraft.recipientCount} onClick={publish}><Send size={15}/>{currentDraft.kind==='exercise'?'Publish local exercise':channel==='sms'?'Send reviewed SMS':'Publish reviewed advisory'}</button>{!currentDraft.recipientCount&&<p className="coastal-fine">No subscribers match. Subscribe a browser to an area to test local delivery.</p>}{delivery&&<p role="status" className="coastal-message">{delivery}</p>}</>}</section></div>}
  {tab==='inbox'&&(subscription?<Inbox subscription={subscription} onRemove={()=>{localStorage.removeItem(STORAGE);setSubscription(null);}}/>:<section className="coastal-panel subscription-panel"><span className="eyebrow">WARNINGS FOR YOUR CHOSEN AREA</span><h2>Keep an area inbox</h2><p>Subscribe this browser to <strong>{location.label}</strong>. The local server saves rounded coordinates and your consent so it can match reviewed warning areas.</p><label>Phone for future SMS delivery (optional)<input aria-label="Subscription phone" type="tel" placeholder="+91…" value={phone} onChange={e=>setPhone(e.target.value)}/></label><p className="coastal-fine">SMS requires provider setup and operator verification of your opt-in. Adding a phone number does not send a message.</p><label className="tool-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I consent to saving this area{phone?' and phone number':''} on this computer for area alerts. I can unsubscribe and delete it from this browser.</label><button className="coastal-button" disabled={!consent||busy} onClick={saveSubscription}>{busy?'Saving…':'Subscribe this browser'}</button></section>)}
  <footer className="coastal-source-links">{status?.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>)}<Link to="/dashboard/explore">Back to weather map →</Link></footer>
  </div>;
}
