import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CircleMarker, Popup, Polyline, Rectangle } from 'react-leaflet';
import { CycloneMap } from '../components/maps/CycloneMap';
import { SatelliteBaseLayer } from '../components/maps/SatelliteBaseLayer';
import { useCyclone } from '../hooks/useCyclone';
import { useResearchResource, selectResearchCase, formatValue as fmt, utc, type CasesResponse } from '../services/research';
import type { ActiveCyclone } from '../types/cyclone';

function Status({ error, ready }: { error: string; ready: boolean }) { return error ? <p className="research-notice" role="alert">{error}</p> : !ready ? <p role="status">Loading research data…</p> : null; }
interface ArchiveRecord { id: string; name: string; season: number; maxWind: number | null; totalSteps: number; startDate: string; modelCases: number }
export function ResearchArchive() {
  const { data, error } = useResearchResource<{ storms: ArchiveRecord[] }>('/historical/catalog');
  const { data: caseData } = useResearchResource<CasesResponse>('/research/cases');
  const [query, setQuery] = useState(''); const [year, setYear] = useState('ALL'); const [selected, setSelected] = useState(''); const [selectionError, setSelectionError] = useState('');
  const { data: detail, error: detailError } = useResearchResource<{ data: ActiveCyclone }>(`/historical/${selected || '2007151N14072'}/replay`);
  const rows = data?.storms.filter(s => (year === 'ALL' || s.season === Number(year)) && `${s.name} ${s.id}`.toLowerCase().includes(query.toLowerCase())) || [];
  const storm = detail?.data;
  const researchCase = caseData?.cases.find(c => c.stormId === storm?.id);
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">NOAA IBTRACS · LOCAL ARCHIVE</span><h2>Real storms. Their recorded tracks.</h2><p>{data?.storms.length ?? '…'} North Indian Ocean storms from your local 1980–2025 CSV. Wind uses the IMD / NEWDELHI field consistently; missing observations remain blank.</p></div><Status error={error} ready={!!data}/>
    <div className="research-controls"><input aria-label="Search storm archive" placeholder="Search storm name or IBTrACS ID" value={query} onChange={e => setQuery(e.target.value)}/><select aria-label="Archive year" value={year} onChange={e => setYear(e.target.value)}><option value="ALL">All years</option>{[...new Set(data?.storms.map(s => s.season))].sort((a,b) => b-a).map(y => <option key={y}>{y}</option>)}</select></div>
    <section className="research-panel"><h3>{storm?.name || 'Storm track'} · {storm?.season}</h3><Status error={detailError} ready={!!storm}/><div className="research-map"><CycloneMap center={storm ? [storm.track[0].lat, storm.track[0].lon] : [15,82]} zoom={4}>{storm && <Polyline positions={storm.track.map(p => [p.lat,p.lon])} pathOptions={{ color:'#216e8c' }}/>}</CycloneMap></div><p className="research-caption">Full historical track · {storm?.track.length ?? 0} observations. This archive view includes the storm’s full lifetime.</p>{researchCase && <button className="research-button" onClick={async () => { try { await selectResearchCase(researchCase.id); setSelectionError(''); } catch { setSelectionError('Could not open research replay.'); } }}>Use this storm in research replay</button>}{selectionError && <p role="alert">{selectionError}</p>}<div className="research-links"><Link to="/dashboard/forecast">Open selected forecast →</Link></div></section>
    <section className="research-panel research-table"><h3>{rows.length} matching storms</h3><table><thead><tr><th>Storm</th><th>Year</th><th>Peak IMD wind</th><th>Records</th><th>Explore</th></tr></thead><tbody>{rows.slice(0,100).map(s => <tr key={s.id} className={s.id === storm?.id ? 'selected-row' : ''}><td>{s.name}<small>{s.id}</small></td><td>{s.season}</td><td>{fmt(s.maxWind,0)} kt</td><td>{s.totalSteps}</td><td><button onClick={() => setSelected(s.id)}>View track</button></td></tr>)}</tbody></table>{rows.length>100 && <p>Showing the first 100 matches. Filter by year or name to narrow the archive.</p>}{!rows.length && <p>No matching storms. Try another name or year.</p>}</section></div>;
}

interface FormationData { data: { issuedAt: string; description: string; threshold: { threshold: number }; cells: { id:string; lat:number; lon:number; score:number; sst:number|null; observedOnset:number }[] } }
export function ResearchBasin() {
  const { data, error } = useResearchResource<FormationData>('/basin/risk'); const [truth, setTruth] = useState(false);
  const grid = data?.data; const cells = grid ? [...grid.cells].sort((a,b) => b.score-a.score) : [];
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">FORMATION RESEARCH · +24 HOURS</span><h2>Explore the formation model</h2><p>{grid?.description || 'Choose a historical test case to run the formation classifier on the matching ERA5 grid.'}</p></div><Status error={error} ready={!!data}/>{grid && <><section className="research-panel"><div className="research-row"><h3>ERA5 grid · {utc(grid.issuedAt)}</h3><label><input type="checkbox" checked={truth} onChange={e => setTruth(e.target.checked)}/>Show recorded threshold onsets</label></div><div className="research-map"><CycloneMap center={[15,78]} zoom={4}>{cells.map(c => <Rectangle key={c.id} bounds={[[c.lat-2.5,c.lon-2.5],[c.lat+2.5,c.lon+2.5]]} pathOptions={{ color:'#2b7795',weight:1,fillOpacity:.06+.7*c.score }}><Popup>Cell {c.id}<br/>Model score: {c.score.toFixed(4)}<br/>SST: {fmt(c.sst)} °C</Popup></Rectangle>)}{truth && cells.filter(c => c.observedOnset===1).map(c => <CircleMarker key={c.id} center={[c.lat,c.lon]} radius={7} pathOptions={{color:'#af7330'}}><Popup>Observed threshold onset within 24h</Popup></CircleMarker>)}</CycloneMap></div><p className="research-caption">Darker cells have higher model scores. Scores are uncalibrated and must not be read as public warning probabilities. Threshold: {grid.threshold.threshold.toFixed(4)}, selected on validation F1.</p></section><section className="research-panel research-table"><h3>Highest scoring cells</h3><table><thead><tr><th>5° cell</th><th>Centre</th><th>Model score</th><th>Mean SST</th></tr></thead><tbody>{cells.slice(0,12).map(c => <tr key={c.id}><td>{c.id}</td><td>{c.lat}°N, {c.lon}°E</td><td>{c.score.toFixed(4)}</td><td>{fmt(c.sst)} °C</td></tr>)}</tbody></table></section></>}</div>;
}

interface Performance { metrics: Record<string,Record<string,Record<string,number>>>; training:{train:string;validation:string;test:string}; models:{name:string;status:string;artifact?:string}[]; limitations:string[] }
export function ResearchModels() {
  const { data, error } = useResearchResource<Performance>('/models/performance');
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">EVIDENCE BEFORE ACCURACY CLAIMS</span><h2>Models & held-out results</h2><p>Metrics below come from the saved research run, with storms separated across time partitions. All active models have a 24-hour horizon.</p></div><Status error={error} ready={!!data}/>{data && <><div className="research-metrics"><article><span>Test wind MAE</span><strong>{fmt(data.metrics.intensity.test.mae_knots,2)} <small>knots</small></strong><p>{data.metrics.intensity.test.rows} cases · {data.metrics.intensity.test.storms} storms</p></article><article><span>Test track mean error</span><strong>{fmt(data.metrics.track.test.mean_error_km,1)} <small>km</small></strong><p>{data.metrics.track.test.rows} cases · {data.metrics.track.test.storms} storms</p></article><article><span>Formation test recall</span><strong>{fmt(data.metrics.formation.test.recall*100,1)}<small>%</small></strong><p>Precision {fmt(data.metrics.formation.test.precision*100,1)}% · {data.metrics.formation.test.positives} positive cell-times</p></article></div>
    <section className="research-panel research-table"><h3>Training, validation & test</h3><table><thead><tr><th>Partition</th><th>Years</th><th>Wind MAE / persistence</th><th>Track error</th><th>Formation F1</th></tr></thead><tbody>{(['train','validation','test'] as const).map(s => <tr key={s}><td>{s}</td><td>{data.training[s]}</td><td>{fmt(data.metrics.intensity[s].mae_knots,2)} / {fmt(data.metrics.intensity[s].persistence_mae_knots,2)} kt</td><td>{fmt(data.metrics.track[s].mean_error_km)} km</td><td>{fmt(data.metrics.formation[s].f1,3)}</td></tr>)}</tbody></table><p>Formation training metrics use sampled negatives; validation and test retain all eligible cells. Lower regression errors are better.</p></section>
    <section className="research-panel research-table"><h3>Presentation architecture & implementation status</h3><table><thead><tr><th>Model</th><th>Status</th></tr></thead><tbody>{data.models.map(m => <tr key={m.name}><td>{m.name}</td><td>{m.status}<small>{m.artifact}</small></td></tr>)}</tbody></table></section><div className="research-notice">{data.limitations.map(l => <p key={l}>{l}</p>)}</div></>}</div>;
}

interface Manifest { archive:{rows:number;storms:number;firstYear:number;lastYear:number;filename:string}; training:{train:string;validation:string;test:string}; sources:{name:string;status:string;description:string}[]; files:Record<string,string> }
export function ResearchSources() {
  const { data, error } = useResearchResource<Manifest>('/research/manifest');
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">VECTOR MINDS · DATA PIPELINE</span><h2>Know what powers each result</h2><p>The website serves your saved datasets and fitted preprocessing artifacts through a local FastAPI inference service.</p></div><Status error={error} ready={!!data}/>{data && <><div className="research-metrics"><article><span>North Indian Ocean archive</span><strong>{data.archive.storms} <small>storms</small></strong><p>{data.archive.rows.toLocaleString()} observations · {data.archive.firstYear}–{data.archive.lastYear}</p></article><article><span>Reanalysis training period</span><strong>1990–2002</strong><p>Validation 2003–2005 · test 2006–2008</p></article><article><span>Forecast horizon</span><strong>24 <small>hours</small></strong><p>Formation, track and sustained wind</p></article></div><section className="research-panel research-table"><table><thead><tr><th>Source</th><th>Status</th><th>Use</th></tr></thead><tbody>{data.sources.map(s => <tr key={s.name}><td>{s.name}</td><td>{s.status}</td><td>{s.description}</td></tr>)}</tbody></table></section><section className="research-panel"><h3>Preprocessing & safeguards against leakage</h3><p>IBTrACS units are parsed and IMD wind is kept in knots. Targets are joined at exactly +24 hours. ERA5 inputs are extracted at the issue time. Median imputation, missing-value indicators and feature scaling use saved objects fitted only on training rows. Models are selected using validation results; the website runs those existing models without fitting on the selected test case.</p><p>Surface ERA5 data do not include upper-air wind shear or mid-level humidity. Those fields remain unavailable. No pressure forecast, satellite detector or impact estimate is invented to fill an empty panel.</p><div className="research-links"><a href="https://www.ncei.noaa.gov/products/international-best-track-archive" target="_blank" rel="noreferrer">NOAA IBTrACS ↗</a><a href="https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels" target="_blank" rel="noreferrer">ERA5 source ↗</a><Link to="/dashboard/models">Model evaluation →</Link></div><details><summary>Artifact checksums</summary><div className="research-table"><table><tbody>{Object.entries(data.files).filter(([path]) => path.endsWith('.ubj')).map(([path,hash]) => <tr key={path}><td>{path}</td><td style={{wordBreak:'break-all'}}>{hash}</td></tr>)}</tbody></table></div></details></section></>}</div>;
}

interface Screening { stormName:string;issuedAt:string;method:string;districts:{districtId:string;districtName:string;state:string;distanceKm:number;centroid:[number,number]}[] }
export function ResearchResponse() {
  const { data, error } = useResearchResource<Screening>('/cyclone/ACTIVE/risk');
  const nearby = data?.districts.filter(d => d.distanceKm<=50) || [];
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">RESEARCH SCREENING · NOT AN EVACUATION ORDER</span><h2>Coastal planning context</h2><p>The presentation’s 50 km concept is shown here as a reference-point proximity screen. It cannot identify flooded areas, safe routes, shelters or who should evacuate.</p></div><Status error={error} ready={!!data}/>{data && <section className="research-panel"><h3>{nearby.length} reference centroids within 50 km</h3><p>{data.stormName} · archived issue {utc(data.issuedAt)}</p><p>{data.method}</p><div className="research-table"><table><thead><tr><th>District reference</th><th>State</th><th>Distance to guide line</th></tr></thead><tbody>{nearby.map(d => <tr key={d.districtId}><td>{d.districtName}</td><td>{d.state}</td><td>{d.distanceKm} km</td></tr>)}</tbody></table>{!nearby.length && <p>No reference centroids meet this geometric threshold. This does not establish that coastal areas are safe.</p>}</div></section>}<section className="research-panel"><h3>Follow official local instructions</h3><p>Use verified advisories and district administration instructions for shelter and evacuation decisions. The website does not send SMS or issue public emergency alerts.</p><div className="research-links"><a href="https://rsmcnewdelhi.imd.gov.in/" target="_blank" rel="noreferrer">IMD cyclone advisories ↗</a><a href="https://sachet.ndma.gov.in/" target="_blank" rel="noreferrer">NDMA SACHET alerts ↗</a></div></section></div>;
}

export function ResearchSatellite() {
  const { cyclone } = useCyclone(); const [dateOverride, setDateOverride] = useState<{issue:string;value:string}|null>(null); const [layer, setLayer] = useState('MODIS_Terra_CorrectedReflectance_TrueColor');
  const issue=cyclone?.currentPosition.timestamp.slice(0,10) || '2007-06-04'; const date=dateOverride?.issue===issue?dateOverride.value:issue;
  return <div className="research-page"><div className="research-intro"><span className="eyebrow">NASA GIBS · VISUAL CONTEXT</span><h2>View the clouds around the selected storm</h2><p>Daily satellite composites are for visual inspection. They are not fed into the XGBoost model. EfficientNet and ConvLSTM need an aligned training dataset and trained checkpoints before inference can be enabled.</p></div><section className="research-panel"><div className="research-controls"><label>Imagery date <input aria-label="Satellite imagery date" type="date" min="2000-02-24" max={new Date().toISOString().slice(0,10)} value={date} onChange={e => setDateOverride({issue,value:e.target.value})}/></label><select aria-label="Satellite sensor" value={layer} onChange={e => setLayer(e.target.value)}><option value="MODIS_Terra_CorrectedReflectance_TrueColor">MODIS Terra true colour</option><option value="MODIS_Aqua_CorrectedReflectance_TrueColor">MODIS Aqua true colour</option></select></div><div className="research-map"><CycloneMap center={cyclone ? [cyclone.currentPosition.lat,cyclone.currentPosition.lon] : [15,82]} zoom={4} showLayerControl={false}><SatelliteBaseLayer key={`${layer}-${date}`} layerName={layer} date={date} maxNativeZoom={9}/></CycloneMap></div><p className="research-caption">NASA daily composite · {date} · requires internet; blank areas can indicate missing coverage. A composite does not represent the exact issue hour.</p></section></div>;
}

export function ResearchAbout() { return <div className="research-page"><div className="research-intro"><span className="eyebrow">VECTOR MINDS · SIH26070</span><h2>Cyclone intelligence for research and preparedness</h2><p>This implementation connects the data, preprocessing, inference and dashboard stages described in your presentation.</p></div><section className="research-panel"><h3>What works today</h3><p>Browse the local IBTrACS archive, select a held-out ERA5 test case, run 24-hour XGBoost forecasts, inspect formation scores, compare predictions with recorded outcomes and explore coastal proximity.</p><h3 style={{marginTop:24}}>What still needs development</h3><p>Aligned satellite training inputs for EfficientNet and ConvLSTM; validated pressure, landfall and surge models; fresh operational model inputs; and live road-closure / shelter-occupancy data. A reviewed local inbox and configurable SMS advisory relay are now available under Evacuation & area alerts. These do not issue automatic public evacuation orders.</p><div className="research-links"><Link to="/dashboard/system">Inspect data sources →</Link><Link to="/dashboard/models">Review measured model skill →</Link></div></section></div>; }

