import { useAsyncResource } from '../hooks/useAsyncResource';
import { useCallback, useState } from 'react';
import { ArrowUpRight, Search, MapPin, Info, Radio, Backpack, House, RefreshCw } from 'lucide-react';
import { fetchCoastalDistrictRoster, fetchDistrictRiskAnalysis } from '../services/riskService';
import { useCyclone } from '../hooks/useCyclone';
import { coastalDistricts } from '../data/mockDistricts';
const tiers=[{key:'RED',title:'Red',label:'Within 50 km',description:'Reference centroid within 50 km of the straight forecast guide line.'},{key:'ORANGE',title:'Orange',label:'Within 150 km',description:'Reference centroid between 50 and 150 km from the forecast guide line.'},{key:'YELLOW',title:'Yellow',label:'Within 300 km',description:'Reference centroid between 150 and 300 km from the forecast guide line.'}];
export default function WarningsImpact(){
 const {cyclone}=useCyclone();const [search,setSearch]=useState('');const [state,setState]=useState('ALL');const [level,setLevel]=useState('ALL');const [refresh,setRefresh]=useState(0);
 const stormId=cyclone?.id||'ACTIVE';const issue=cyclone?.currentPosition.timestamp;
 const fetcher=useCallback(async()=>{const [districts,result]=await Promise.all([fetchCoastalDistrictRoster(),fetchDistrictRiskAnalysis(stormId)]);return {districts,risk:result?.stormId&&result.stormId!=='STANDBY'?result:null,issue,refresh};},[stormId,issue,refresh]);
 const resource=useAsyncResource(fetcher);const loading=resource.loading;const risk=resource.data?.risk??null;const roster=resource.data?.districts?.length?resource.data.districts:coastalDistricts;
 const assessments=new Map(risk?.districts.map(d=>[d.districtId,d])||[]);const sourceRoster=risk?.districts.length?risk.districts.map(d=>({id:d.districtId,name:d.districtName,state:d.state,centroid:d.centroid})):roster;
 const states=[...new Set(sourceRoster.map(d=>d.state))].sort();const rows=sourceRoster.filter(d=>(state==='ALL'||state===d.state)&&(level==='ALL'||assessments.get(d.id)?.warningLevel===level)&&`${d.name} ${d.state}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));
 return <div className="public-warnings"><div className="public-source-note" role="status"><Info size={20}/><div><strong>{loading?'Checking for district assessments…':risk?'Historical proximity screen available':'Current district assessments are unavailable'}</strong><p>{risk?`Historical research for ${risk.stormName} at ${cyclone?.currentPosition.timestamp || 'selected issue time'}. Distances use reference centroids and a straight +24h guide line; they are not hazard or evacuation zones.`:'You can still explore the coastal district directory. Missing data does not mean there is no risk.'}</p></div><button onClick={()=>setRefresh(r=>r+1)} disabled={loading}><RefreshCw size={15}/>Refresh</button></div>
 <section className="warning-explainer"><div className="section-intro"><span className="eyebrow">A LITTLE CONTEXT GOES A LONG WAY</span><h2>Understand coastal proximity.</h2><p>These illustrative distance bands describe the replay geometry. They do not estimate local wind, surge, landfall or public warning levels.</p></div><div className="warning-tier-grid">{tiers.map(t=><button key={t.key} className={`warning-tier tier-${t.key.toLowerCase()} ${level===t.key?'chosen':''}`} aria-pressed={level===t.key} onClick={()=>setLevel(level===t.key?'ALL':t.key)}><div><span className="tier-dot"/><strong>{t.title}</strong><span className="tier-count">{risk?risk.districts.filter(d=>d.warningLevel===t.key).length:'—'}</span></div><h3>{t.label}</h3><p>{t.description}</p><span className="tier-foot">{risk?'View assessed districts':'Assessment data unavailable'}<ArrowUpRight size={15}/></span></button>)}</div></section>
 <div className="public-warning-columns"><section className="district-panel" id="district-directory"><div className="directory-heading"><div><span className="eyebrow">LOCAL INFORMATION</span><h2>Find your coastal district</h2><p>Search by district or state to see available assessments.</p></div><MapPin size={25}/></div><div className="district-controls"><label className="district-search"><Search size={17}/><input aria-label="Search district or state" placeholder="Search district or state…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter by state" value={state} onChange={e=>setState(e.target.value)}><option value="ALL">All coastal states</option>{states.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter by model tier" value={level} onChange={e=>setLevel(e.target.value)}><option value="ALL">All model tiers</option>{['RED','ORANGE','YELLOW','GREEN'].map(t=><option key={t} value={t}>{t.toLowerCase()}</option>)}</select></div>
 <div className="district-table-wrap"><table><caption className="sr-only">Coastal district directory and available model assessments</caption><thead><tr><th>District / State</th><th>Model assessment</th><th>Distance to guide line</th><th>Record type</th></tr></thead><tbody>{rows.map(d=>{const a=assessments.get(d.id);return <tr key={d.id}><td><strong>{d.name}</strong><small>{d.state}</small></td><td><span className={`district-badge ${a?'badge-'+a.warningLevel.toLowerCase():''}`}>{a?a.warningLevel==='RED'?'≤50 km':a.warningLevel==='ORANGE'?'50–150 km':a.warningLevel==='YELLOW'?'150–300 km':'>300 km':'Not available'}</span></td><td>{a?`${a.distanceKm} km`:'—'}</td><td>{a?'Historical replay':'—'}</td></tr>})}</tbody></table>{!rows.length&&<div className="directory-empty"><Search size={24}/><h3>No matching districts</h3><p>Try another district, state or model tier.</p><button onClick={()=>{setSearch('');setState('ALL');setLevel('ALL')}}>Clear filters</button></div>}</div><div className="directory-footer">{rows.length} districts shown <span>{risk?'Geometric screen · not official warnings':'Directory only · no current assessment'}</span></div></section>
 <aside className="preparedness-panel"><div className="preparedness-art" aria-hidden="true"><House size={56} strokeWidth={1}/><span className="art-sun"/><span className="art-wave"/></div><span className="eyebrow">SMALL STEPS. BETTER PREPARED.</span><h2>Make a plan<br/>before you need it.</h2><p>Keep trusted information and essential items within reach.</p><div className="preparation-item"><Radio size={21}/><div><h3>Choose trusted updates</h3><p>Follow IMD and your local disaster management authority.</p></div></div><div className="preparation-item"><Backpack size={21}/><div><h3>Keep essentials together</h3><p>Make important documents, regular medicines and emergency contacts easy to find.</p></div></div><a href="https://ndma.gov.in/Natural-Hazards/Cyclone" target="_blank" rel="noreferrer">Read NDMA cyclone guidance <ArrowUpRight size={17}/></a></aside></div>
 <section className="public-faq"><span className="eyebrow">GOOD QUESTIONS, CLEAR ANSWERS</span><h2>Understanding this page</h2>{[['Is this an official cyclone warning?','No. Cyclone AI is an independent research platform. Its model assessments support exploration and do not replace advisories from IMD or your local authority.'],['What does “Not available” mean?','A current model assessment was not received for that district. It is not an all-clear or a statement that conditions are safe.'],['Why can the forecast change?','New observations can change the estimated track and intensity. Check the issue time and follow updates rather than relying on a single forecast.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></div>
}
