import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CircleMarker, Marker, Popup, Polyline, useMapEvents } from 'react-leaflet';
import { divIcon } from 'leaflet';
import { Wind, CloudRain, Gauge, Thermometer, Cloud, Play, Pause, MapPin, ArrowRight, Layers } from 'lucide-react';
import { CycloneMap } from '../components/maps/CycloneMap';
import { useResearchResource, formatValue as fmt, utc, type ResearchForecast } from '../services/research';
import { useCyclone } from '../hooks/useCyclone';
import './coastal-tools.css';

type Field = 'wind_speed_10m' | 'precipitation' | 'pressure_msl' | 'temperature_2m' | 'cloud_cover';
interface WeatherPoint { lat:number; lon:number; gridLat:number; gridLon:number; times:string[]; values:Record<string,(number|null)[]>; units:Record<string,string> }
interface WeatherData { source:string; sourceUrl:string; fetchedAt:string; model:string; points:WeatherPoint[]; samplingNote?:string }
const layers = [{id:'wind_speed_10m',name:'Wind',unit:'kt',icon:Wind,min:0,max:50},{id:'precipitation',name:'Rain',unit:'mm/h',icon:CloudRain,min:0,max:15},{id:'pressure_msl',name:'Pressure',unit:'hPa',icon:Gauge,min:980,max:1030},{id:'temperature_2m',name:'Temperature',unit:'°C',icon:Thermometer,min:15,max:40},{id:'cloud_cover',name:'Clouds',unit:'%',icon:Cloud,min:0,max:100}] as const;
function colour(value:number,field:Field) { const spec=layers.find(l=>l.id===field)!; const t=Math.max(0,Math.min(1,(value-spec.min)/(spec.max-spec.min))); return `hsl(${210-t*190} 65% ${48-t*8}%)`; }
function PickLocation({onPick}:{onPick:(p:[number,number])=>void}) { useMapEvents({click:e=>onPick([Number(e.latlng.lat.toFixed(3)),Number(e.latlng.lng.toFixed(3))])}); return null; }

function WindArrow({point,index,moving}:{point:WeatherPoint;index:number;moving:boolean}) {
  const speed=point.values.wind_speed_10m[index]; const direction=point.values.wind_direction_10m[index];
  if(speed==null || direction==null) return null;
  const icon=divIcon({className:'weather-wind-icon',iconSize:[46,46],iconAnchor:[23,23],html:`<div class="weather-wind-arrow ${moving?'moving':''}" style="transform:rotate(${direction+180}deg)"><svg width="46" height="46" viewBox="0 0 46 46"><path class="wind-trace" d="M23 39V10"/><path d="m17 18 6-8 6 8"/></svg></div>`});
  return <Marker position={[point.lat,point.lon]} icon={icon}><Popup>10 m wind: {fmt(speed)} kt<br/>From {fmt(direction,0)}° · GFS model</Popup></Marker>;
}

function ArchiveOverlay() {
  const {cyclone}=useCyclone(); const {data}=useResearchResource<ResearchForecast>('/cyclone/ACTIVE/predictions'); const f=data?.data;
  if(!cyclone || !f || f.issuedAt!==cyclone.currentPosition.timestamp || data.stormId!==cyclone.id) return null;
  return <><Polyline positions={cyclone.track.map(p=>[p.lat,p.lon])} pathOptions={{color:'#553c82',weight:3}}/><CircleMarker center={[f.forecastPoints[0].lat,f.forecastPoints[0].lon]} radius={9} pathOptions={{color:'#a53c73'}}><Popup>Archived XGBoost +24h endpoint<br/>Issued {utc(f.issuedAt)}<br/>Not the current GFS forecast.</Popup></CircleMarker></>;
}

export default function WeatherExplorer() {
  const [location,setLocation]=useState<[number,number]>([12.911,88.925]);
  const [region,setRegion]=useState<[number,number]>([13,89]);
  const [draftLat,setDraftLat]=useState('12.911'); const [draftLon,setDraftLon]=useState('88.925');
  const [field,setField]=useState<Field>('wind_speed_10m'); const [hour,setHour]=useState(0); const [playing,setPlaying]=useState(false); const [motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches); const [archived,setArchived]=useState(false); const [formError,setFormError]=useState('');
  const {data,error}=useResearchResource<WeatherData>(`/weather/point?lat=${location[0]}&lon=${location[1]}`);
  const {data:grid,error:gridError}=useResearchResource<WeatherData>(`/weather/grid?lat=${region[0]}&lon=${region[1]}`);
  const point=data?.points[0]; const maxHour=(point?.times.length||1)-1; const index=Math.min(hour,maxHour); const selectedTime=point?.times[index]; const spec=layers.find(l=>l.id===field)!;
  const pick=(p:[number,number])=>{if(p[0]<-90||p[0]>90||p[1]<-180||p[1]>180)return;setLocation(p);setDraftLat(String(p[0]));setDraftLon(String(p[1]));setFormError('');};
  useEffect(()=>{if(!playing||maxHour<1)return; const timer=window.setInterval(()=>setHour(h=>(h+1)%(maxHour+1)),1000);return()=>window.clearInterval(timer);},[playing,maxHour]);
  const submit=(e:React.FormEvent)=>{e.preventDefault();const lat=Number(draftLat),lon=Number(draftLon);if(!draftLat.trim()||!draftLon.trim()||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180){setFormError('Enter a valid latitude and longitude.');return;}pick([lat,lon]);};
  return <div className="weather-explorer"><div className="coastal-heading"><div><span className="eyebrow">THE WEATHER, IN CONTEXT</span><h1>Explore the next 72 hours.</h1><p>Choose a layer. Move through time. Click the map for a local forecast.</p></div><span className="source-pill">GFS <small>via Open-Meteo</small></span></div>
    <div className="weather-toolbar"><div className="weather-layer-tabs" aria-label="Weather layer">{layers.map(l=><button key={l.id} aria-pressed={field===l.id} className={field===l.id?'selected':''} onClick={()=>setField(l.id)}><l.icon size={17}/>{l.name}</button>)}</div><label className="tool-check"><input type="checkbox" checked={motion} onChange={e=>setMotion(e.target.checked)}/>Wind animation</label></div>
    <div className="weather-workspace"><section className="weather-map-frame" aria-label="Interactive weather map"><CycloneMap center={location} zoom={5}><PickLocation onPick={pick}/>{grid?.points.map(p=>{const i=selectedTime?p.times.indexOf(selectedTime):-1;const v=i>=0?p.values[field][i]:null;return v==null?null:<CircleMarker key={`${p.lat},${p.lon}`} center={[p.lat,p.lon]} radius={22} pathOptions={{color:colour(v,field),fillColor:colour(v,field),fillOpacity:.5,weight:1}}><Popup>{spec.name}: {fmt(v)} {spec.unit}<br/>{selectedTime&&utc(selectedTime)}<br/>GFS sample point</Popup></CircleMarker>;})}{field==='wind_speed_10m'&&grid?.points.map(p=><WindArrow key={`${p.lat},${p.lon}`} point={p} index={selectedTime?p.times.indexOf(selectedTime):-1} moving={motion}/>)}<CircleMarker center={location} radius={7} pathOptions={{color:'#fff',fillColor:'#143c51',fillOpacity:1,weight:3}}><Popup>Selected location<br/>{location[0]}°, {location[1]}°</Popup></CircleMarker>{archived&&<ArchiveOverlay/>}</CycloneMap><div className="map-explainer"><Layers size={14}/><span>25 regional samples · 3° spacing<br/><small>{!grid&&!gridError?'Loading regional samples…':'Point samples, not radar or flood extent'}</small></span></div></section>
    <aside className="weather-location-panel"><span className="eyebrow"><MapPin size={13}/> SELECTED LOCATION</span><h2>{location[0].toFixed(3)}° / {location[1].toFixed(3)}°</h2><form className="coordinate-form" onSubmit={submit}><label>Latitude<input aria-label="Weather latitude" type="number" min="-90" max="90" step="any" required value={draftLat} onChange={e=>setDraftLat(e.target.value)}/></label><label>Longitude<input aria-label="Weather longitude" type="number" min="-180" max="180" step="any" required value={draftLon} onChange={e=>setDraftLon(e.target.value)}/></label><button className="coastal-button" type="submit">View location</button></form>{formError&&<p role="alert">{formError}</p>}
    {error?<div role="alert" className="coastal-message">{error}<button onClick={()=>window.dispatchEvent(new Event('cyclone-refresh'))}>Try again</button></div>:!point?<p role="status">Loading the GFS forecast…</p>:<><p className="weather-valid">{selectedTime&&utc(selectedTime)}</p><div className="weather-main-value">{fmt(point.values[field][index])}<small>{spec.unit}</small></div><p>{spec.name} at the selected forecast hour</p><dl className="weather-details"><div><dt>Wind / gust</dt><dd>{fmt(point.values.wind_speed_10m[index])} / {fmt(point.values.wind_gusts_10m[index])} kt</dd></div><div><dt>Precipitation</dt><dd>{fmt(point.values.precipitation[index])} mm/h</dd></div><div><dt>Pressure</dt><dd>{fmt(point.values.pressure_msl[index])} hPa</dd></div><div><dt>Temperature</dt><dd>{fmt(point.values.temperature_2m[index])} °C</dd></div><div><dt>Cloud cover</dt><dd>{fmt(point.values.cloud_cover[index],0)}%</dd></div></dl></>}
      <button className="coastal-button secondary" disabled={location[0]<0||location[0]>35||location[1]<50||location[1]>105} onClick={()=>setRegion([Math.round(location[0]),Math.round(location[1])])}>Load regional samples here</button><small>Regional layers cover the North Indian Ocean. Point forecasts work worldwide.</small><Link className="coastal-link" to={`/dashboard/response?lat=${location[0]}&lon=${location[1]}`}>Plan for this location <ArrowRight size={15}/></Link></aside></div>
    <section className="weather-timeline" aria-label="Forecast timeline"><button aria-label={playing?'Pause forecast timeline':'Play forecast timeline'} disabled={!point} onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><div><div className="timeline-labels"><strong>{selectedTime?utc(selectedTime):'Loading forecast hours'}</strong><span>Hourly · UTC</span></div><input aria-label="Forecast hour" type="range" min={0} max={maxHour} value={index} disabled={!point} onChange={e=>{setHour(Number(e.target.value));setPlaying(false);}}/><div className="timeline-labels"><span>{point?.times[0]?utc(point.times[0]):'—'}</span><span>{point?.times[maxHour]?utc(point.times[maxHour]):'—'}</span></div></div><div className="weather-legend"><span>{spec.name} · {spec.unit}</span><div style={{background:`linear-gradient(90deg,${colour(spec.min,field)},${colour((spec.min+spec.max)/2,field)},${colour(spec.max,field)})`}}/><span>{spec.min}<b>{spec.max}+</b></span></div></section>
    {gridError&&<p className="coastal-message" role="status">Regional overlay unavailable: {gridError} The point forecast is fetched separately.</p>}
    <div className="weather-footnotes"><p>{data?`Fetched ${utc(data.fetchedAt)}. `:''}GFS weather and archived XGBoost cyclone forecasts are separate datasets. Wind arrows show model direction; animation is illustrative. Precipitation is the preceding hour’s total. Selected forecast coordinates are sent to Open-Meteo.</p><label className="tool-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Overlay dated research track</label>{archived&&<p className="coastal-message">Purple track: historical research case, not a current GFS cyclone path. <Link to="/dashboard/forecast">View its issue time and forecast.</Link></p>}<a href="https://open-meteo.com/en/docs/gfs-api" target="_blank" rel="noreferrer">Open-Meteo / GFS data and attribution ↗</a></div>
    {point&&<details className="weather-hourly"><summary>Hourly forecast table</summary><div className="research-table"><table><thead><tr><th>Valid time (UTC)</th><th>Wind kt</th><th>Gust kt</th><th>Rain mm/h</th><th>Pressure hPa</th></tr></thead><tbody>{point.times.map((t,i)=><tr key={t} className={i===index?'selected-row':''}><td>{utc(t)}</td><td>{fmt(point.values.wind_speed_10m[i])}</td><td>{fmt(point.values.wind_gusts_10m[i])}</td><td>{fmt(point.values.precipitation[i])}</td><td>{fmt(point.values.pressure_msl[i])}</td></tr>)}</tbody></table></div></details>}
  </div>;
}
